### PR TITLE
Humidity offset

### PR DESCRIPTION
**Pull request by bspranger**
Adding humidity offset for temp/humidity sensors.

Please review before i merge because i am traveling and working on a tablet.

### CODE REVIEW

**Comment by tmleafs** [comment]
You have put required:true which is also set like that for temperature setting, This means the user will have to put something to be able to save the settings page, either remove it or add defaultValue: 0 to both

**Comment by bspranger** [comment]
Please take another look, i added defaultValue: 0

**Comment by tmleafs** [comment]
Looks good but cant test as I don't have either of these devices

**Comment by veeceeoh** [comment]
I don't have a Temp/Humidity sensor either (yet!), but looking at the code, I wonder why not do the the `null` value check on `settings.humidOffset` up at the top of the function so you can get rid of the `if (settings.humidOffset)` conditional? That also allows you to get rid of `pct.round(2)` as well, like this:

```
private Map parseHumidity(String description){
    def pct = (description - "humidity: " - "%").trim()

    if (!(settings.humidOffset)) {
        settings.humidOffset = 0
    }
    if (pct.isNumber()) {
        pct =  Math.round(new BigDecimal(pct + settings.humidOffset))
        }
        def result = [
            name: 'humidity',
            value: pct,
            unit: "%",
            isStateChange:true,
            descriptionText : "${device.displayName} Humidity is ${pct}%"
        ]
        return result
    }
    return [:]
 }
```

**Comment by alecm** [comment]
So - I started testing this - have one each of the old and the new - old one is paired, new one needs to be repaired so it will be a day or so until I can actually test.  
There's a small UI issue with both the temperature and the humidity offset preferences at least on iPhone.  The keyboard that comes up has a little + and - at top and the numbers under it.  All cool.  But you can't actually type a +3 - the plus key is inactive.  You can, however, type a '-' sign.     Unless someone knows a way to 'activate'  the plus key - I suggest we change the instructions to say '3' or '-3'  rather than '+3' or  '-3'.

**Comment by alecm** [comment]
Actually - I'm guessing I should open a different issue for that - will do so

**Comment by veeceeoh** [comment]
@alecm - I've actually been working on cleaning up the preferences section for all DTHs. In my testing I noticed the same thing about the + key not working on my iPhone, and was planning on changing that description accordingly (get rid of any mention of "+").

I am waiting on putting in my commits until this pull request and the one for removing the refresh function get merged, though.

**Comment by bspranger** [comment]
Sounds like I should merge this so we can clean up all the preferences...  agree?

**Comment by veeceeoh** [comment]
Sure!

**Comment by alecm** [comment]
yup!

**Pull request merged**
