### PR TITLE
Use runIn() to add a button held state for WebCoRE users

### PR DESCRIPTION
**Pull request by veeceeoh**
Because this is so different from what @tmleafs is working on, I've done as a Pull Request on his Pull.

I have no real way to test this on my Aqara button, so please have a look, and give it a try. I put in a bunch of debug log messages to help identify any issues that may arise.

I'm also looking into whether doing a sendEvent to change the state of "momentary" has any use. I notice it's in the old a4refillpad button DTH.

### CODE REVIEW

**Comment by foz333** [comment]
paired a new 'original' button
tried a clicks then a hold a couple times

clicking

**Comment by veeceeoh** [comment]
Thanks @foz333!

It looks like I need to fix a few things. The countdown value shouldn't come out as null, even if the preference setting is blank. 

Also, it looks like one button press was missed. I see On/Off: 0 & 1, then just 1, then 0 & 1, then 0 & 1. Weird.

**Comment by veeceeoh** [comment]
So I have always had some difficulty with the IDE simulator, but I managed to get it loaded and working so I could troubleshoot my code.

And, in the simulator, it works! Here is the log from a long press and then a short press:

screen shot 2018-02-16 at 3 37 23 pm

Notes on what I did:

**Changes**
• changed attribute `countdown` to `stillHeld`
• in Momentary mode, if button is released, `parseButtonMessage()` will set "pressed" state first, before setting "released" state - which replicates the behavior of the old a4refillpad DTH, while still adding the new additional "released" state that users can also take advantage of
• added debug messages to display the current button state value at different points in the code
• changed the default countdown timer to 5 seconds (for testing with the simulator - feel free to change the preference setting in your testing)

Fixes
• the renamed attribute `stillHeld` is now type String because I could not get conditionals to work correctly with it set as type boolean (Groovy sometimes seems really quirky to me)
• the "starting countdown in XXX seconds" debug message now correctly displays the number of seconds
• changed runIn ternary to an [Elvis operator](https://en.wikipedia.org/wiki/Elvis_operator)! ()
• removed attribute "batteryLevel" because it is not used
• moved some debug messages to below the line they refer to
• changed `createEvent` to `sendEvent` because it wasn't setting the button state - it seems the only time createEvent should be used is at the end of main `parse()` function
• used `device.currentValue("xxx")` as the only way that correctly pulls the state values for "button" and "stillHeld"

If anyone can test this on an _actual Xiaomi button_, then we can see if it's ready to be shared on the ST Community forums as a beta version to do some testing with.

**Comment by emilakered** [comment]
I did a little testing! Working great, with one "exception". The button reports "pressed" instead of "pushed", something my Webcore Piston can't parse - it is still looking for "pushed", and "pushed" is the reported capability (see screenshot).

But, when I changed "result = getContactResult("pressed")" to "result = getContactResult("pushed")" on row 193, everything works brilliantly! I guess one of the ways would work, either make sure "pressed" is reported as a capability to Webcore, or send "pushed" instead if that dosen't interfere with anything else.

webcore

**Comment by emilakered** [comment]
Okay, after some further testing it seems like the timers "collide" and get confused if the button is pressed repeatedly. Moe often than not it becomes "held" actions, even though every single press is just momentary. I can look into log files later today or tomorow if needed, just on my way out!

**Comment by emilakered** [comment]
Okay, I managed to grab a quick log before heading out. Here I pressed the button every ~0,5 seconds. Held time is set to 1 second in settings. About 80 % af the presses subjetivly registered correctly, but a few were picked up as "held". 

---

12:04:15: debug Knapp, Amiralen: Parse returned [name:button, value:released, data:[buttonNumber:1], descriptionText:Knapp, Amiralen was released, isStateChange:true]
12:04:15: debug BUTTON TEST: Created map to change to RELEASED state
12:04:15: debug BUTTON TEST: Creating map to change to released state
12:04:15: debug BUTTON TEST: Button current state is <pushed>
12:04:15: debug BUTTON TEST: Created event: [name:button, value:pushed, data:[buttonNumber:1, microDeviceTile:[type:standard, backgroundColor:#00a0dc]], descriptionText:Knapp, Amiralen was pushed, isStateChange:true, displayed:true, linkText:Knapp, Amiralen]
12:04:14: debug BUTTON TEST: Countdown not finished, created map to change to PRESSED state
12:04:14: debug BUTTON TEST: Creating map to change to pushed state
12:04:14: debug BUTTON TEST: Button current state is <released>
12:04:14: debug BUTTON TEST: Set stillHeld to <false>
12:04:14: debug BUTTON TEST: Momentary detected button release
12:04:14: debug Knapp, Amiralen: Parsing 'on/off: 1'
12:04:15: debug BUTTON TEST: Button NOT held, so no action taken
12:04:15: debug BUTTON TEST: Countdown finished, and stillHeld is <false>
12:04:14: debug Knapp, Amiralen: Parse returned [:]
12:04:14: debug BUTTON TEST: Started countdown of 1 seconds
12:04:14: debug BUTTON TEST: Set stillHeld to <true>
12:04:14: debug BUTTON TEST: Button current state is <released>
12:04:14: debug BUTTON TEST: Momentary detected button press
12:04:14: debug Knapp, Amiralen: Parsing 'on/off: 0'
12:04:14: debug BUTTON TEST: Button NOT held, so no action taken
12:04:14: debug BUTTON TEST: Countdown finished, and stillHeld is <false>
12:04:14: debug Knapp, Amiralen: Parse returned [name:button, value:released, data:[buttonNumber:1], descriptionText:Knapp, Amiralen was released, isStateChange:true]
12:04:14: debug BUTTON TEST: Created map to change to RELEASED state
12:04:14: debug BUTTON TEST: Creating map to change to released state
12:04:14: debug BUTTON TEST: Button current state is <pushed>
12:04:14: debug BUTTON TEST: Created event: [name:button, value:pushed, data:[buttonNumber:1, microDeviceTile:[type:standard, backgroundColor:#00a0dc]], descriptionText:Knapp, Amiralen was pushed, isStateChange:true, displayed:true, linkText:Knapp, Amiralen]
12:04:14: debug BUTTON TEST: Countdown not finished, created map to change to PRESSED state
12:04:14: debug BUTTON TEST: Creating map to change to pushed state
12:04:14: debug BUTTON TEST: Button current state is <released>
12:04:14: debug BUTTON TEST: Set stillHeld to <false>
12:04:14: debug BUTTON TEST: Momentary detected button release
12:04:14: debug Knapp, Amiralen: Parsing 'on/off: 1'
12:04:13: debug Knapp, Amiralen: Parse returned [:]
12:04:13: debug BUTTON TEST: Started countdown of 1 seconds
12:04:13: debug BUTTON TEST: Set stillHeld to <true>
12:04:13: debug BUTTON TEST: Button current state is <released>
12:04:13: debug BUTTON TEST: Momentary detected button press
12:04:13: debug Knapp, Amiralen: Parsing 'on/off: 0'
12:04:13: debug Knapp, Amiralen: Parse returned [name:button, value:released, data:[buttonNumber:1], descriptionText:Knapp, Amiralen was released, isStateChange:true]
12:04:13: debug BUTTON TEST: Created map to change to RELEASED state
12:04:13: debug BUTTON TEST: Creating map to change to released state
12:04:13: debug BUTTON TEST: Button current state is <held>
12:04:13: debug BUTTON TEST: Set stillHeld to <false>
12:04:13: debug BUTTON TEST: Momentary detected button release
12:04:13: debug Knapp, Amiralen: Parsing 'on/off: 1'
12:04:13: debug BUTTON TEST: Button current state is <held>
12:04:13: debug BUTTON TEST: Sent event: [name:button, value:held, data:[buttonNumber:1], descriptionText:Knapp, Amiralen was held, isStateChange:true, displayed:true, linkText:Knapp, Amiralen]
12:04:13: debug BUTTON TEST: Created map to change to HELD state
12:04:13: debug BUTTON TEST: Creating map to change to held state
12:04:13: debug BUTTON TEST: Countdown finished, and stillHeld is <true>
12:04:12: debug Knapp, Amiralen: Parse returned [:]
12:04:12: debug BUTTON TEST: Started countdown of 1 seconds
12:04:12: debug BUTTON TEST: Set stillHeld to <true>
12:04:12: debug BUTTON TEST: Button current state is <released>
12:04:12: debug BUTTON TEST: Momentary detected button press
12:04:12: debug Knapp, Amiralen: Parsing 'on/off: 0'
12:04:12: debug BUTTON TEST: Button current state is <held>
12:04:12: debug BUTTON TEST: Sent event: [name:button, value:held, data:[buttonNumber:1], descriptionText:Knapp, Amiralen was held, isStateChange:true, displayed:true, linkText:Knapp, Amiralen]
12:04:12: debug BUTTON TEST: Created map to change to HELD state
12:04:12: debug BUTTON TEST: Creating map to change to held state
12:04:12: debug BUTTON TEST: Countdown finished, and stillHeld is <true>
12:04:11: debug Knapp, Amiralen: Parse returned [:]
12:04:11: debug BUTTON TEST: Started countdown of 1 seconds
12:04:11: debug BUTTON TEST: Set stillHeld to <true>
12:04:11: debug BUTTON TEST: Button current state is <released>
12:04:11: debug BUTTON TEST: Momentary detected button press
12:04:11: debug Knapp, Amiralen: Parsing 'on/off: 0'
12:04:11: debug Knapp, Amiralen: Parse returned [name:button, value:released, data:[buttonNumber:1], descriptionText:Knapp, Amiralen was released, isStateChange:true]
12:04:11: debug BUTTON TEST: Created map to change to RELEASED state
12:04:11: debug BUTTON TEST: Creating map to change to released state
12:04:11: debug BUTTON TEST: Button current state is <pushed>
12:04:11: debug BUTTON TEST: Created event: [name:button, value:pushed, data:[buttonNumber:1, microDeviceTile:[type:standard, backgroundColor:#00a0dc]], descriptionText:Knapp, Amiralen was pushed, isStateChange:true, displayed:true, linkText:Knapp, Amiralen]
12:04:11: debug BUTTON TEST: Countdown not finished, created map to change to PRESSED state
12:04:11: debug BUTTON TEST: Creating map to change to pushed state
12:04:11: debug BUTTON TEST: Button current state is <released>
12:04:11: debug BUTTON TEST: Set stillHeld to <false>
12:04:11: debug BUTTON TEST: Momentary detected button release
12:04:11: debug Knapp, Amiralen: Parsing 'on/off: 1'
12:04:11: debug Knapp, Amiralen: Parse returned [:]
12:04:11: debug BUTTON TEST: Started countdown of 1 seconds
12:04:11: debug BUTTON TEST: Set stillHeld to <true>
12:04:11: debug BUTTON TEST: Button current state is <released>
12:04:11: debug BUTTON TEST: Momentary detected button press
12:04:10: debug Knapp, Amiralen: Parsing 'on/off: 0'
12:04:10: debug Knapp, Amiralen: Parse returned [name:button, value:released, data:[buttonNumber:1], descriptionText:Knapp, Amiralen was released, isStateChange:true]
12:04:10: debug BUTTON TEST: Created map to change to RELEASED state
12:04:10: debug BUTTON TEST: Creating map to change to released state
12:04:10: debug BUTTON TEST: Button current state is <pushed>
12:04:10: debug BUTTON TEST: Created event: [name:button, value:pushed, data:[buttonNumber:1, microDeviceTile:[type:standard, backgroundColor:#00a0dc]], descriptionText:Knapp, Amiralen was pushed, isStateChange:true, displayed:true, linkText:Knapp, Amiralen]
12:04:10: debug BUTTON TEST: Countdown not finished, created map to change to PRESSED state
12:04:10: debug BUTTON TEST: Creating map to change to pushed state
12:04:10: debug BUTTON TEST: Button current state is <released>
12:04:10: debug BUTTON TEST: Set stillHeld to <false>
12:04:10: debug BUTTON TEST: Momentary detected button release
12:04:10: debug Knapp, Amiralen: Parsing 'on/off: 1'
12:04:10: debug Knapp, Amiralen: Parse returned [:]
12:04:10: debug BUTTON TEST: Started countdown of 1 seconds
12:04:10: debug BUTTON TEST: Set stillHeld to <true>
12:04:10: debug BUTTON TEST: Button current state is <released>
12:04:10: debug BUTTON TEST: Momentary detected button press
12:04:10: debug Knapp, Amiralen: Parsing 'on/off: 0'
12:04:09: debug Knapp, Amiralen: Parse returned [name:button, value:released, data:[buttonNumber:1], descriptionText:Knapp, Amiralen was released, isStateChange:true]
12:04:09: debug BUTTON TEST: Created map to change to RELEASED state
12:04:09: debug BUTTON TEST: Creating map to change to released state
12:04:09: debug BUTTON TEST: Button current state is <pushed>
12:04:09: debug BUTTON TEST: Created event: [name:button, value:pushed, data:[buttonNumber:1, microDeviceTile:[type:standard, backgroundColor:#00a0dc]], descriptionText:Knapp, Amiralen was pushed, isStateChange:true, displayed:true, linkText:Knapp, Amiralen]
12:04:09: debug BUTTON TEST: Countdown not finished, created map to change to PRESSED state
12:04:09: debug BUTTON TEST: Creating map to change to pushed state
12:04:09: debug BUTTON TEST: Button current state is <released>
12:04:09: debug BUTTON TEST: Set stillHeld to <false>
12:04:09: debug BUTTON TEST: Momentary detected button release
12:04:09: debug Knapp, Amiralen: Parsing 'on/off: 1'
12:04:09: debug Knapp, Amiralen: Parse returned [:]
12:04:09: debug BUTTON TEST: Started countdown of 1 seconds
12:04:09: debug BUTTON TEST: Set stillHeld to <true>
12:04:09: debug BUTTON TEST: Button current state is <released>
12:04:09: debug BUTTON TEST: Momentary detected button press
12:04:09: debug Knapp, Amiralen: Parsing 'on/off: 0'
12:04:09: debug BUTTON TEST: Button NOT held, so no action taken
12:04:09: debug BUTTON TEST: Countdown finished, and stillHeld is <false>
12:04:08: debug Knapp, Amiralen: Parse returned [name:button, value:released, data:[buttonNumber:1], descriptionText:Knapp, Amiralen was released, isStateChange:true]
12:04:08: debug BUTTON TEST: Created map to change to RELEASED state
12:04:08: debug BUTTON TEST: Creating map to change to released state
12:04:08: debug BUTTON TEST: Button current state is <pushed>
12:04:08: debug BUTTON TEST: Created event: [name:button, value:pushed, data:[buttonNumber:1, microDeviceTile:[type:standard, backgroundColor:#00a0dc]], descriptionText:Knapp, Amiralen was pushed, isStateChange:true, displayed:true, linkText:Knapp, Amiralen]
12:04:08: debug BUTTON TEST: Countdown not finished, created map to change to PRESSED state
12:04:08: debug BUTTON TEST: Creating map to change to pushed state
12:04:08: debug BUTTON TEST: Button current state is <released>
12:04:08: debug BUTTON TEST: Set stillHeld to <false>
12:04:08: debug BUTTON TEST: Momentary detected button release
12:04:08: debug Knapp, Amiralen: Parsing 'on/off: 1'
12:04:08: debug Knapp, Amiralen: Parse returned [:]
12:04:08: debug BUTTON TEST: Started countdown of 1 seconds
12:04:08: debug BUTTON TEST: Set stillHeld to <true>
12:04:08: debug BUTTON TEST: Button current state is <released>
12:04:08: debug BUTTON TEST: Momentary detected button press
12:04:08: debug Knapp, Amiralen: Parsing 'on/off: 0'
12:04:08: debug BUTTON TEST: Button NOT held, so no action taken
12:04:08: debug BUTTON TEST: Countdown finished, and stillHeld is <false>
12:04:07: debug Knapp, Amiralen: Parse returned [name:button, value:released, data:[buttonNumber:1], descriptionText:Knapp, Amiralen was released, isStateChange:true]
12:04:07: debug BUTTON TEST: Created map to change to RELEASED state
12:04:07: debug BUTTON TEST: Creating map to change to released state
12:04:07: debug BUTTON TEST: Button current state is <pushed>
12:04:07: debug BUTTON TEST: Created event: [name:button, value:pushed, data:[buttonNumber:1, microDeviceTile:[type:standard, backgroundColor:#00a0dc]], descriptionText:Knapp, Amiralen was pushed, isStateChange:true, displayed:true, linkText:Knapp, Amiralen]
12:04:07: debug BUTTON TEST: Countdown not finished, created map to change to PRESSED state
12:04:07: debug BUTTON TEST: Creating map to change to pushed state
12:04:07: debug BUTTON TEST: Button current state is <released>
12:04:07: debug BUTTON TEST: Set stillHeld to <false>
12:04:07: debug BUTTON TEST: Momentary detected button release
12:04:07: debug Knapp, Amiralen: Parsing 'on/off: 1'
12:04:07: debug Knapp, Amiralen: Parse returned [:]
12:04:07: debug BUTTON TEST: Started countdown of 1 seconds
12:04:07: debug BUTTON TEST: Set stillHeld to <true>
12:04:07: debug BUTTON TEST: Button current state is <released>
12:04:07: debug BUTTON TEST: Momentary detected button press
12:04:07: debug Knapp, Amiralen: Parsing 'on/off: 0'
12:04:07: debug BUTTON TEST: Button NOT held, so no action taken
12:04:07: debug BUTTON TEST: Countdown finished, and stillHeld is <false>
12:04:06: debug Knapp, Amiralen: Parse returned [name:button, value:released, data:[buttonNumber:1], descriptionText:Knapp, Amiralen was released, isStateChange:true]
12:04:06: debug BUTTON TEST: Created map to change to RELEASED state
12:04:06: debug BUTTON TEST: Creating map to change to released state
12:04:06: debug BUTTON TEST: Button current state is <pushed>
12:04:06: debug BUTTON TEST: Created event: [name:button, value:pushed, data:[buttonNumber:1, microDeviceTile:[type:standard, backgroundColor:#00a0dc]], descriptionText:Knapp, Amiralen was pushed, isStateChange:true, displayed:true, linkText:Knapp, Amiralen]
12:04:06: debug BUTTON TEST: Countdown not finished, created map to change to PRESSED state
12:04:06: debug BUTTON TEST: Creating map to change to pushed state
12:04:06: debug BUTTON TEST: Button current state is <released>
12:04:06: debug BUTTON TEST: Set stillHeld to <false>
12:04:06: debug BUTTON TEST: Momentary detected button release
12:04:06: debug Knapp, Amiralen: Parsing 'on/off: 1'
12:04:06: debug Knapp, Amiralen: Parse returned [:]
12:04:06: debug BUTTON TEST: Started countdown of 1 seconds
12:04:06: debug BUTTON TEST: Set stillHeld to <true>
12:04:06: debug BUTTON TEST: Button current state is <released>
12:04:06: debug BUTTON TEST: Momentary detected button press
12:04:06: debug Knapp, Amiralen: Parsing 'on/off: 0'

**Comment by veeceeoh** [comment]
@emilakered - Thanks so much for testing this code! It helps a lot because I don't have the "original" button myself... yet. With many thanks to @alecm, one is on its way to me now! So I'll be able to do testing with the code myself next week.

> But, when I changed "result = getContactResult("pressed")" to "result = getContactResult("pushed")" on row 193, everything works!

Yeah, that was just a mistake on my part. It should have been "pushed", so I'll fix that line of code.

> Okay, after some further testing it seems like the timers "collide" and get confused if the button is pressed repeatedly. More often than not it becomes "held" actions, even though every single press is just momentary.

This is inevitable, due to the way the code works. But I don't expect people to normally press the button repeatedly in less than one or two-second intervals. Do you ever need to use it that way?

To be honest, I'm impressed that it's working as well as it does with you test, considering a number of factors:
1. You set the countdown to 1 second for the check if the button is held. That is a rather short delay.
2. You were pressing and releasing the button once or twice every second.
3. This device driver runs in the "cloud" so there is definitely a varying length of a lag
4. I've added a lot of debug log output, which can slow things down a bit.
5. SmartThings doesn't guarantee schedule-based commands such as `runIn()` to be 100% accurate.

Looking at the log, I noticed that some of the runIn() countdowns took over 1 second to complete, and also from second 11 to 12, I see two button "pressed" (on/off: 0) messages recieved consecutively.

So, unless some log messages were not output, this means that a button "released" message was missed / dropped by the hub. Not good, but there's not much we can do about it. The device handler can only work with the messages or data that the hub passes on to it.

From this test, it appears that:
1. The code is working correctly (as best as it can)
2. A countdown time of 1 second is probably too short for "normal" use
3. Repeatedly pressing/releasing the button once or more a second will not be possible
4. The `runIn()` countdown time may not be exact every time
5. The hub may be missing button pressed/released messages

Of these observations,
No. 2 can be addressed by setting range for the preference setting with a minimum of 2 seconds,
No. 3 can be addressed by explaining the limitations of the device handler code (maybe take a poll to ask users if they actually use buttons that way?), and
No. 4 can be addressed by explaining that feedback of a successful "held" button (such as observing that a light or device turned on) is a good way to know the "held" command was sent and it's okay to release the button, but
No. 5 is something we can't really do much about

I'll have to wait until I get that button next week to test, but I plan on comparing the reliability of the method used in the a4refillpad code as compared to using the `runIn()` method I came up with, and look at whether there's any way the a4refillpad code can be improved.

**Comment by veeceeoh** [comment]
Okay, newest update:

**Fixes**
• Changed "pressed" to "pushed" on line 192
• removed `state.battery = 0` from `installed()` and `configure()` because I have discovered it serves no purpose

**Changes**
• commented out all "BUTTON TEST" debug log messages except for the one in `getContactResult()` for feedback on what state change is about to happen

**Comment by emilakered** [comment]
You are absolutely right, it's not normal usage to press the button that often. I only did it to try to force misbehaviour. Same goes for the 1 second, as you say 2 seconds is probably minimum for a consitent result. :)

**Comment by alecm** [comment]
For way too frequent push - I think the mode is called “impatientForElevator” - but I can’t find a good reference in the Zigbee Cluster Library

**Comment by emilakered** [comment]
Okay, I have been doing more testing today (with the latest revision).

With the original a4refillpad code I would say I get the correct behaviour (pushed or held) about 95 % of the time. If I don't, the command is usually missed altogether, not interpreted wrong. That is true even with rapid presses, several per second. As we concluded before that isn't normal usage, but with a 1 year old at home it is still something that.. well, happens, whether I like it or not. :P

With the current Xiaomi Button code (the one comitted in the master branch, without held), I get a somewhat different behaviour. The button still works most of the time, but then goes into some kind of hiatus for a few seconds. After that, a lot of commands are queue up and executed in rapid succession.

For example, If I use first push to turn on a lamp to 50 %, then a second to 100 % and a third to turn off again in a cycle. Even if I pause for several seconds between pushes, sometimes it still misses one and executes it much later.

With the experimental code worked on here, I get the same behaviour as with the main branch code. The difference is that when commands are "queued up", it becomes a mixed bag of pushed and held actions at execution. This is true even if I pause between presses, instead of forcing bad behaviour via "1 year old simluation". The end result is that maybe 50-75 % of the commands are interpreted correcly.

To me it looks like I maybe have a weak signal in the Zigbee mesh, so I tried with different buttons. I get more or less the same result, where a4refillpad seems to work more consistent. I will try to disconnect all reperaters and thereby force the buttons to talk directly to my hub (if they don't now), maybe that will make a difference.

---

I hope the information provided is of some help! I'm really grateful for everyones work here, and it's meant as feedback - not criticism! Hugs, love and all that. Looking forward to @veeceeoh getting a button so we can compare real results, nice job there @alecm.

**Comment by veeceeoh** [comment]
No worries @emilakered - I understand it's feedback, and very useful too!

I'm starting to think that the button just isn't 100% reliable with SmartThings, but I'll be very curious to see how well it works for me after the one @alecm sent arrives.

**Comment by veeceeoh** [comment]
I may have found the reason for the strange behavior with the button, from [this post](https://forum.athom.com/discussion/comment/57091/#Comment_57091) on a Athom Homey forum thread. Most importantly from the post:

> The switch/button wil send different events (values) for hold, release, single, double, triple, and quadruple+ clicks - because of this a single click has a slight lag.

**Comment by veeceeoh** [comment]
After doing testing I'm pretty convinced the issues of inconsistent behavior are due to the above mentioned lag on single click. I've posted about this back at the main comment thread of Issue #93.

**Comment by veeceeoh** [comment]
So, I'm sorry to say that after a bunch of testing, I don't think the `runIn()` method to determine button pressed vs hold is going to work. And maybe not the original method in a4refillpad's DTH.

This all has to do with the multi-click capability of the button. In fact, even though I'm happy to help come up with a happy medium for the SmartThings original button DTH, I won't ever be using myself.

That's because I'll be using it with my new Hubitat hub, which unlike the SmartThings hub, passes on ALL button press messages to make use of AND does everything locally so there is NO delay. I will explain more soon in a (somewhat off-topic) issue here on GitHub.

Anyhow, using the Hubitat hub, I discovered the behavior of the Xiaomi "original" button. Here's a handy chart (with some oversimplification of the messages received):

Type of press | Message(s) Received
------------ | -------------
Single click | press (00), release (01)
Double-click | press (02)
Triple-click | press (03)
Quadruple-click | press (04)
Hold | press (00)
Double-click w/hold on 2nd click | press (02)
Triple-click w/hold on 3rd click | press (03)
Quad-click w/hold on 4th click | press (04)
Release after any hold | release (01)

_Note: "Click" means very quick press & release, exactly the same as with a computer mouse._

**Behaviors observed during testing**

1.  _None_ of the multi-clicks return the "release (01)" message unless the button is held down on the _last_ click
2. If the button is multi-clicked _too slowly_ then the "release (01)" message is _not_ sent between clicks, only once, after the last click. For example, if I Quadruple-click slowly, I see _four_ consecutive "press (00)" messages followed by a single "release (01)" message.

Behavior 2 is what totally messes things up for SmartThings users, because the multi-click messages are ignored and not passed on to the DTH. So what happens is "release" messages are skipped, and if the countdown/delay to decide on "held" is short enough, the DTH will set the "held" state when the user was expecting "pressed". And that is why neither method of determining what kind of press can be called "held" won't work 100%.

**Comment by bspranger** [comment]
Does hubitat support Google voice assistant?

Are the Xiaomi sensors staying connected to the hubitat?

How does hubitat compare to ST so far?

**Comment by gn0st1c** [comment]
i moved to Hubitat as well :)

google assistant support is on their "top priority to do list".
mi sensors had some issues but with the firmware upgrade all seems fine now.

**Comment by bspranger** [comment]
Hubitat updated their firmware to fix the Xiaomi integration?

**Comment by foz333** [comment]
No hubitat for EU yet... sadly.

**Comment by emilakered** [comment]
Great work @veeceeoh, thank you for that!

I have been running the DTH in master (momentary mode) parallel with the old a4refillpad for about a week now, on different buttons at home - all with single click applications, no hold function. My empirical result is that the old DTH is more reliable, although not 100 % as discussed before. The new one just "stacks" commands more often, probably due to the nature of the hardware. Even a single, isolated short, click can take a few seconds sometimes, and multiple click with ample space between can make the "last one" execute seconds after the other ones.

It's hard to explain, but the a4refillpad is more hit and miss. It works, or it doesn't work. Then I can try again more or less instantly. The new DTH in master is more click, wait and see, try again if needed. It might be something with my specific configuration, but.. well, that's what I have. :)

**Comment by gn0st1c** [comment]
@bspranger : no, firmware update was mostly for upgrades to Zigbee/Zwave functionalities.

**Comment by veeceeoh** [comment]
I just changed the code again, using a new method to store the status of the countdown: a state variable, which is persistent across executions of the code. I also removed the "released" event completely from momentary mode.

This may or may not improve the reliability and responsiveness of the `runIn()` method. I won't be able to test it until tomorrow.

Changes
• No using `state.countdownActive` instead of an attribute to track whether the `runIn()` countdown is active
• Removed "released" event from momentary mode code - now only generates "pushed" & "held" events
• Changed the logic of conditional for button release in momentary mode
• Removed nearly all debug log messages

**Comment by veeceeoh** [comment]
I had a chance to do a little testing yesterday with my revised code. I will have to spend a bit more time, but what I am seeing is telling me that no momentary button implementation based on the press / release messages from the Xioami button will ever work 100% unless the device handler code is executed locally.

This is because when the button is _clicked_, the "press" and "released" messages come so closely to each other that sometimes the device handler finishes executing the code for "released" BEFORE the execution finishes for the "press" message. 

This can be seen pretty clearly in the log just by clicking the button over and over again.. I also saw that sometimes a "press" message is dropped. So the cloud execution of the device handler makes the use of this button unreliable.

The reason why the a4refillpad method works a little better is that it only takes action on a "released" message. But the reversal of "released" and "pressed" would still mean that some erroneous "held" events will get produced.

To double check on this, I am just going to create a simple routine that only outputs a log entry showing the message received from the button, with no other actions taken. If I still see "released" messaged coming before "pressed" then that will confirm this is an issue related to the slight time delays due to running the device handler code in the cloud.

**Comment by foz333** [comment]
@veeceeoh  Okay... if the release being picked up or processed before the press is the problem. Maybe we can just account for it with trinary logic.  

Have a new int variable = has_been_pressed (HBP) = 0 as default.

Everytime button pressed... HBP+=1

In execution of release check HBP
If 0 do nothing
If 1 do press or hold
If 2 or more press.

That should at least take out the false positives and get your method working with a4 reliability or better.

Sorry if that'd not clear, or is a load of rubbish. stuck on phone these days and my brain a little switched off too.

**Comment by veeceeoh** [comment]
@foz333 - Thanks for the suggestion, but in doing a bunch of testing of new code with a so-called global "state" variable, if I just keep track of how many events occur, regardless of whether a button pressed is processed before the button release or vice-versa, it only made the reliability worse. I also tried keep track of things using a sendEvent() but that also worked terribly. 

All of this relates directly back to the lag/delay associated with cloud-execution of the code, and that every message received is processed in a separate execution of the DTH.

I am going to close this pull request, and make a new one with code that integrates a4refillpad's original method for momentary press functionality with events that allow WebCoRE users to make use of the button.

**Comment by emilakered** [comment]
Just a lite pong from me as well! Like @veeceeoh I have ordered a Hubitat (the EU version, hurray!) and I will probably migrate to that one over time. In the meantime, I have replaced the "critical" Xiaomi buttons with a few Z-Wave ones from Hank that are more reliable and reports "held" in a way SmartThings can actually understand.

So, in short, this isn't really an issue for me anymore as I have bought myself workarounds. I will only use the Xiaomi buttons for "non-critical" applications, and probably only with single push without hold. :)

**Comment by foz333** [comment]
@emilakared Wait a minute... EU version. 
Is this new, can you sent me a link where I can buy this?

**Comment by veeceeoh** [comment]
I am going to submit a new Pull Request which incorporates the a4refillpad method of comparing `lastPressed` time to time of button release to determine whether to send a "pushed" or "held" event.

Closing this Pull Request now...

**Pull request closed without merging**
