### PR TITLE
Code clean-up & added empty2x2 tile (=spacer)

### PR DESCRIPTION
**Pull request by ronvandegraaf**
I made changes to Aqara device handlers:

- Code clean-up
- Added empty2x2 tile as spacer ([SmartThings example](https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/tile-ux/tile-basic-standard.src/tile-basic-standard.groovy))
- Tested device handlers

Can't modify or test any original sensors, because I don't own any.

### CODE REVIEW

**Comment by tmleafs** [comment]
I prefer the way it is 
screenshot_20180131-140950 small

the rest of the code just seems to be removing tabs for spaces which imo is wrong

**Comment by ronvandegraaf** [comment]
iOS is showing '--' in every small tile in the current DH, and this way we keep the code a little cleaner/smaller with only one spacer.

**Comment by gn0st1c** [comment]
i second @tmleafs. replacing tabs with spaces is very very very wrong :)

https://www.youtube.com/watch?v=SsoOG6ZeyUI

**Comment by tmleafs** [comment]
I was very close to posting the same video @gn0st1c 

Well smartthings cant get anything right can they in my happy world iOS wouldn't exist 

Im getting closer to not having to make changes to the master code for my use, its currently just swapping lastPress/Opened with lastcheckin on the layout, So anything anything that breaks my OCD will be met with resistance

**Comment by ronvandegraaf** [comment]
- Changed spaces to tabs
- Tested Aqara device handlers

**Comment by gn0st1c** [comment]
@tmleafs, i almost never use other's DTH as is, as they are not ocd friendly :)
i format them as i like, then watch the differences and apply them myself.

**Comment by veeceeoh** [comment]
My take: I am here to help make these DTH the best they can be for all users, not for beautifully formatted code that many (most?) users have no idea about. 

That goal is platform-agnostic, and I'm not interested in slighting groups of people. I want my solutions to work for everyone.

I am not a coder by trade, but appreciate the indents to help me read through the code, so I let my text editor help me on that front. Multi-spaces to tabs is a grep/search-replace fix away; it doesn't bother me.

**Comment by veeceeoh** [comment]
I tested code with the "empty2x2" standardTile on my iOS device, and it looks fine.

As to the position / order of tiles debate, we are all perfectly capable of changing code to our preferences. What do most (non-coding) users prefer? Does the ST community forums have a poll/vote post feature?

**Comment by bspranger** [comment]
I don't know guys....  this could be the most epic code ever but tabs...  really?  Come on.
I am not sure I can merge this one...
😁

I am used to using a real editor and beautifiers, using the phone and the smartthings IDE sure makes editing difficult. 

I guess the fact that most phones don't have a tab key would be one reason to keep spaces over tabs.

**Comment by tmleafs** [comment]
i agree when ever code by me is added it will be tabbed but there no need to change the whole document 
close this. the 2x2 tile can be resubmitted and the only reason I except that is the iOS bug displaying "--" on single tiles

**Comment by bspranger** [comment]
Closing due to tab vs spaces.

**Pull request closed without merging**
