### PR TITLE
Slight change to Battery reporting in recently 

### PR DESCRIPTION
**Pull request by alecm**
This is discussed in 

https://github.com/bspranger/Xiaomi/issues/104

Basically want to change text from 

descriptionText : "${device.displayName} is at ${roundedPct}% (${rawVolts} Volts)"

to

descriptionText : "${device.displayName} Battery at ${roundedPct}% (${rawVolts} Volts)"

so that the word "Battery" shows in the update.   See images and explanation on the issue. 

Figured I'd try my hand at a multi-file commit/pull. 

Please review.

Thanks!

### CODE REVIEW

**Comment by veeceeoh** [comment]
Looks great. I only realized I forgot to change that text just after the new icons update was merged, so I very quickly went through and changed the text for the battery event. I wasn't thinking about the word "battery" being missing, but what you've done is what I had intended it to be.

I say make the change to the smoke sensor DTH as well, since it's using the new battery icon.

Then, by all means, merge it!

PS., Nice work on the multi-file Pull Request!

**Comment by alecm** [comment]
oh - cool - it automatically added the commit for the smoke sensor to the pull request!!  Didn't know it would do that.

**Comment by alecm** [comment]
I'm merging - will test all for compiling in the IDE (I don't have all devices but that I can do)

**Comment by alecm** [comment]
ok - I think we're ok - was able to update all from repo without erroring out.

Closing.

**Pull request merged**
