### PR TITLE
Updated round button DTH with Held

### PR DESCRIPTION
**Pull request by veeceeoh**
I have reincorporated a4refillpad's method to determine whether a button "pushed" or "held" event is sent, based on the difference in time between pressing the button and releasing it.

By all reports, this method seems to be the most reliable, but still not 100% because of some press & release messages being parsed in reversed order, or even dropped by the hub. However, it's main limitation is that after pressing the button, nothing will happen until you release it. So even if the `waittoHeld` preference is set to 2 seconds, if the button is held for 10 seconds, the button "held" event only gets sent at 10 seconds, when the button is physically released.

Note that I've re-worked a4refillpad's code to remove redundancies, and to make sure the main `parse(String description)` routine is the only one calling `createEvent()`.

To try to make this DTH more versatile for WebCoRE users, I've also added `lastReleased` and `lastReleasedDate` events that are triggered when the button is physically released.

I haven't tested this DTH yet, and it really must be tested before it's released.

If this code works well enough, then I can use it to build the DTH for the new Aqara button model.

### CODE REVIEW

**Comment by veeceeoh** [comment]
I did some testing and made some fixes / changes:

Fixes
• Added missing `if {}` condition brackets

Changes
• Added `lastButtonMssg` attribute to send events any time the button is pressed or released
• changed the time difference calculation to compare time of last `lastButtonMssg` event to current time at button release
• changed default button held time preference setting to 2 seconds

Button pressed vs held seems to be around 95% accurate and reliable, with a `waittoHeld` setting of 2 seconds or longer. This is as good as it's going to get as far as I can tell, because the ST hub still drops some button press/release messages and also sometimes gets them in reverse.

I would really love it if anyone who uses webCoRE could test this out.

**Comment by veeceeoh** [comment]
Made some changes based on beta user reports and after some researching through the SmartThings Developer Documentation:

Fixes
• added `"Holdable Button"` capability
• removed `"Momentary"` capability because according to SmartThings Developer documentation it is a command capability, only for a switch that can be controlled
• `waittoHeld` preference setting is now `type: "decimal"` to allow for millisecond precision 
• changed calculation of `holdTimeMillisec` in `createButtonEvent()` to allow for millisecond precision
• removed `button` - `released` event from virtual button function, because SmartThings Developer documentation states that only `pushed` and `held` events are supported with the button capability
• changed main tile to display only `pushed` or `held`, to represent the last button event

**Comment by veeceeoh** [comment]
Another update of the code -

I did some more research on methods of timestamps using Groovy. The most accurate way to get a timestamp with milliseconds precision is to use what's called Epoch Time stamp, using the call `now()`, as explained [here](http://docs.smartthings.com/en/latest/smartapp-developers-guide/state.html#other-object-types).

Also, I think it make it easier for webCoRE users to identify the attributes suitable for them to use in Pistons, so I've renamed those to end with ...`CoRE` instead of ...`Date`.

**Changes**
• changed all references to object `nowDate` using `new Date(now).getTime()` to directly call the more precise Epoch Time `now()`
• changed all unnecessary references to object `now` to directly call `formatDate()`
• removed defined objects `now` and `nowDate` because they are no longer used
• All attributes using Epoch Time renamed from `...Date` to `...CoRE`
• changed createEvent of Model name to debug log message
• removed irrelevant comments
• reorganized and edited comments for clarity
• cleaned up code formatting

**Comment by veeceeoh** [comment]
Oh wow, I forgot to mention that I removed the Toggle Mode from the DTH.

We can't use that because the `button` capability no longer supports the `released` state in SmartThings. Only button `pushed` and `held` states are supported.

**Comment by alecm** [comment]
Looks like it's one or the other - my guess is toggle is usually easy enough to implement upstream  (you could flip a virtual switch when button pressed, for example....)

**Comment by veeceeoh** [comment]
Yeah, a toggle function is easily implemented by a SmartApp. ST's Smart Lights App offers this, for example.

But if a button `release` is not supported, then it won't be used by Smart Apps, which is why I've removed it. There's still a custom `LastReleasedwebCoRE` event though, which is for CoRE users.

**Comment by alecm** [comment]
makes sense to me

**Comment by veeceeoh** [comment]
I have been getting positive feedback from some people beta-testing this updated DTH with webCoRE.

However, in my testing I am still seeing some button press/release messages getting dropped, and as a result the calculated difference between a click of the button, waiting, and then clicking it again is sometimes artificially large, resulting in a button `held` event instead of `pushed`.

To minimize on false positives on `held` events, I decided to force any calculated difference that is 10 seconds more than the "wait until held" time setting to send a `pushed` event. This will help increase the overall reliability.

I have also decided to use this beta DTH as a testing ground for another improvement I'd like to implement in all the DTHs: toggles for info & debug log message display preference settings. I will open a new issue on this with more information.

Finally, I reviewed other device handlers for virtual button code and found a method for a happy medium on using the main tile as both a virtual button and to give an indication of the last state of the physical button (`pushed` or `held`).

**Changes / Fixes**
• added logging message display preference settings, with separate toggles for info message output (defaults to ON) and debug message output (defaults to OFF)
• Cleaned up log messages for consistency and assigned them into info / debug groups to work with new logging preference settings
• re-added `capability "Momentary"` to be used by the virtual button tile.
• reworked the main tile and `push()` command code so that pushing the virtual button simulates a single click of the Xiaomi button with a button `pushed` event and the accompanying custom `lastPressed/CoRE` and `lastReleased/CoRE` events - but because button "released" events are not supported, there is no way for the tile to give visual feedback on the press - just look at the events log or logging window if info logging is turned on
• added a failsafe to the "wait until held" calculation to avoid false positives on button "held" - if the calculated difference between button messages more than 10 seconds over the "wait until held" time setting, then a button `pushed` event is sent instead of `held`
• edited some comments for clarity

**Comment by veeceeoh** [comment]
Code updated again. No change in functionality.

**Changes**
• refactored button press handling code to combine redundant calls and remove one layer of nested map call
• applied fixes from updated Aqara button DTH
• cleanup / reformatting of header comment text
• small edits to some info / debug log messages

**Fixes**
• reworked `parseReadAttrMessage()` so that short status report messages are handled correctly, without an error
• added `state.prefsSetCount` to handle default of displaying info log messages from initialization at pairing until users actually saves preference settings.
• changed check on whether `batteryRuntime` attribute is blank to use `device.currentState('batteryRuntime')`
• added `numberOfButtons` = 1 event during `install()` and `configure()`

**Comment by veeceeoh** [comment]
Another update. Besides a few changes, I've added a preference setting to allow a button hold to send a `button 2 pushed` event instead of `button 1 held`, because some Smart Apps are not set up to recognize button held events.

**Changes**
• `attribute "lastCheckinCoRE"` now type `string`
• removed attribute `lastReleased` because it's not needed
• change updateLastPressed() so that a `lastPressed` event is sent both on button and release
• added Button Configuration preferences section explanation text
• changed waittoHeld preference description text
• added new toggle preference to add option of sending `button 2 pushed` event on hold instead of `button 1 held` event
• implemented `holdIsButton2` setting in createButtonEvent()
• refactored code that determines whether to send button pushed or held event
• changed button event description text and log message to be more helpful / precise
• added check of `holdIsButton2` setting in `configure()` and `updated()` to update corresponding `numberOfButtons` value
• added `lastButtonMssg` event on `configure()` to avoid error on first button press after pairing

**Pull request merged**
