### PR TITLE
Remove configure reporting

### PR DESCRIPTION
**Pull request by bspranger**

### CODE REVIEW

**Comment by bspranger** [comment]
Please review, again working on a tablet so easy to make mistakes

**Comment by tmleafs** [comment]
Maybe add spacers to centre lastcheckin and batteryreset

screenshot_20180126-152616 small

> 		valueTile("spacer", "spacer", decoration: "flat", inactiveLabel: false, width: 1, height: 1) {
>         }

and 

>         details(["contact","battery","resetClosed","resetOpen","spacer","lastCheckin", "spacer", "spacer", "batteryRuntime", "spacer"])

**Comment by veeceeoh** [comment]
Here's my suggestion for the Door/Window Sensor and Leak DTHs:

img_2136

change `resetDry`/`resetClosed` & `resetWet`/`resetOpen` tiles to `width: 3, height: 1` and the order of tiles to: `details(["water","battery","lastcheckin","batteryRuntime","resetDry","resetWet"])`

I'd have to see screenshots for the current tile arrangement of other DTHs to make suggestions for those.

**Comment by bspranger** [comment]
I think i will merge this and we can do a cleanup on the arrangement of the tiles.

**Pull request merged**
