### PR TITLE
Overhaul and Standardization of all DTHs

### PR DESCRIPTION
**Pull request by veeceeoh**
Now that I have an Aqara Temp/Humidity sensor to do testing with, I have spent the past 5 hours completely reworking sections of the code to address outstanding issues, and also worked on enhancements including fully integrating @tmleaf's High & Low Temperature tracking code. That last item shoud BE TESTED before this code is considered ready to merge.

Fixes:
• Now uses `zigbee.getEvent` to handle the parsing of humidity reports, which resolves Issue #73
• Temperature reports are also parsed by `zigbee.getEvent`, which "automagically" retrieves the temperature converted into the correct value (including values below 0) in the unit (C or F) as set on the user's hub. One small downside is that `zigbee.getEvent` only produces integer values for temperature reports. This is standard practice on pretty much all other temp sensor DTHs, however. On the plus side, the `zigbee.getEvent` function call allows the DTH code to be significantly shorter.
• lastCheckIn updates are no longer listed in the Events log ("Recently" tab of the ST mobile app) They were flooding the Events log, and 95% of the time happen at the same time as a Temp, Humidity, Pressure, or Battery report, so it's clear that the device has checked in. The Last Checkin tile will still be updated for every one of these events, however. Also if a message is received that can't be parsed, that will show up as a CheckIn event in the Events log.
• Removed some superfluous `debug.log` lines
• Removed unnecessary battery value parse code and fixed model name parse code in the `parseReadAttr()` function to get rid of an array error. It turns out that until the first regular battery report is sent at about 50 minutes after pairing, if the reset button is pressed, it does not send battery voltage data, but rather a short message only containing the model name: "lumi.weather". However, after the first regular battery report, if the reset button is pressed, the sensor sends two messages: the first is a catchall that does contain battery voltage data in addition to other data, and the second is the short message with the model name.
• Moved the `preferences{}` section down to the bottom of `metadata{}`, below `tiles{}`, following the convention of the SmartThings Developer Documentation
• Various small fixes and clean up of the code

Enhancements
• Added the code needed to display the high / low temperatures tracked by @tmleafs' code, following @ronvandegraaf's mock up in Issue #40
• Reworked parts of @tmleafs' high / low temp tracking code, necessary due to the above-listed fixes
• Replaced @tmleafs' cron `schedule()` function method to reset the min/max temps with new code in the `dateFormat()` function that compares the day of month of the previous event with the current event being parsed. The SmartThings Developer Documentation strongly advises against using a cron schedule if it can be avoided, so since the sensor itself produces events at a maximum interval of 50 minutes (for the battery check-in), those can be used to check if it's a new day and then reset the min/max temperature values. We may also want to add a preference setting just like the one for the Changed Battery reset toggle.
• Added code so that when the sensor is first paired, the Battery Changed is set to the current date
• Added a bunch of relevant comments in the code to help people navigate through all its functions

Screenshots (sorry it's an iPad, because it wasn't updated to the new version with the screwed-up UI):

img_0135

img_0136

### CODE REVIEW

**Comment by bspranger** [comment]
Wow,  you've been busy!  I like the changes, but I am not sure about integer value temperature.

**Comment by alecm** [comment]
Amazing work.

I may be wrong - but my understanding is that those who use Centigrade have a harder time with integer only than those with Fahrenheit - because of precision.   

Here's a commentary on it

http://www.theweatherprediction.com/habyhints2/563/

Could those who use Centigrade chime in ? 

Even so - this is so cool!

**Comment by veeceeoh** [comment]
Xiaomi claims these levels of accuracy on the Aqara T/H sensor:

Temperature detection range: -20 - 60 Deg.C ( + / - 0.3 Deg.C )
Humidity detection range: 0 - 100pct RH ( + / - 0.3pct )
Atmospheric pressure detection range: 30 - 110KPa ( + / - 120Pa )

That's a 0.6 Degree C spread (if not actually even more), meaning displaying a reading down including tenths of a degree is just giving the illusion of + / - 0.05 accuracy.

However, after yesterday's crazy coding session, I think I could throw the old code back and then even add a preference setting that lets users choose the display of temperature with or without tenths of a degree.

Anyhow - I really need some people to test out the code to make sure the end-of-the-day "detector" code is working. There's a debug logging line that will output something like "currentDay = 04, oldDay = 04, newDay = 04", and at the first report of any kind after midnight tonight comes in, it should read "currentDay = 04, oldDay = 04, newDay = 05" once, then a debug message of "Resetting daily min/max temp values to current temperature of XX" (XX being the current temp at that time). After that the debug output will be "currentDay = 05, oldDay = 05, newDay = 05".

If I can't figure out how to make it work, I could bring the cron schedule method back in, but it has to be done very carefully to make sure multiple schedules aren't created. For example, it shouldn't be set inside the `updated()` function because that gets called _twice_ every time a user presses save in the preference settings page. Also, using `unschedule()` is frowned upon, because it is a "potentially expensive operation" according to the ST Dev Docs [here](http://docs.smartthings.com/en/latest/smartapp-developers-guide/scheduling.html#best-practices).

If the cron schedule does go back in, it needs adjustment because it was throwing errors for me. The exact line needs to be: `schedule("37 0 0 * * ?", "tempReset")`. for the seconds field, the allowable range is 0-59, so a value of 60 was throwing the error. And for some reason the named handler needs to be between quotes, at least if you go by SmartThings' [Once-a-day schedule code example](https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/smartapps/smartthings/once-a-day.src/once-a-day.groovy). Honestly I'd really rather find a way to use the sensor's own frequent reports as a way to trigger the daily min/max temps reset. On the Aqara sensor, the battery reports faithfully every 50 minutes, so 49 minutes after midnight is the potential maximum largest margin of "error" on triggering the start of a new day of min/max temps. I can live with that and hope others could too.

**Comment by veeceeoh** [comment]
I've posted [a poll](https://community.smartthings.com/t/original-aqara-xiaomi-zigbee-sensors-contact-temp-motion-button-outlet-leak-etc/113253/418?u=veeceeoh) on the bspranger DTH thread on ST Community Forums, to collect others' thoughts on the question of integer vs with tenths of a degree display.

**Comment by alecm** [comment]
Poll is a good idea!

**Comment by alecm** [comment]
That said - I’d suggest questions such as

“How important to you is the ability to display the temperature with one decimal point vs. a whole number?

Not important at all - 1
Somewhat important - 2
Very important - 3

A similar one for 
“How important for you is the ability to switch between whole numbers and one decimal point?”  (Similar scale)

My hunch is that with your current questions most people are going to want the choice by default without thinking it through - hence giving you more work and adding complexity to code you are trying to simplify.

**Comment by veeceeoh** [comment]
Never mind on the need for testing! I just realized I can test the day change code to compare the _minute_ of the previous report with the minute of the current report being parsed. That made testing a lot quicker, and after some tweaks, it seems to be working perfectly:

screen shot 2018-02-04 at 3 19 57 pm

But to be surer, I'm going to change the code to check to every hour, leave the sensor alone and make sure it resets the min/max temps on the first event of each hour.

**Comment by veeceeoh** [comment]
Notes from new commit (revision 2):

**New Fixes**
• removed RequiredAtSetup from preferences{} section (it's only needed for SmartApps)
• reworked of the checkNewDay() routine, which now seems to be working correctly. If you want to test it, on line 361 change "dd" to "HH" to make it check for the hour to change instead of the day of month. Makes testing a lot quicker!
• separated out the routine to update the displayed SECONDARY_CONTROL attribute of the main tile, so that it can be elsewhere besides in the tempReset() function

**New Enhancements**
• added current humidity reading to the displayed SECONDARY_CONTROL attribute of the main tile, including a custom white humidity icon (screenshot below)

**Still to do:**
• rename SECONDARY_CONTROL attribute from minmaxTemps to something more relevant (now that it also includes current humidity
• figure out why the SECONDARY_CONTROL attribute humidity value sometimes gets out of sync with the devices current humidity (as displayed in the 2x2 tile). I believe this may only be happening with numerous / large changes in temp/humidity (like when I blow my breath on the sensor for testing!) and a race condition may be happening that doesn't allow that routine to update quickly enough. Not sure. Any help would be appreciated.
• add back the previous temperature parse routine, and add a preference setting for users to choose between temp displayed as integer and with tenths of degree precision. Based on the poll I did on ST Community forums, it's clear that there's going to be a good split of those who prefer one or the other. So let make them all happy!

img_0137

**Comment by tmleafs** [comment]
could add a high & low for humidity & pressure? Display it all or user configure

**Comment by veeceeoh** [comment]
So based on the state reports from last night for the `currentDay` value I created for the routine that checks if the day of month has changed, I'm quite satisfied it will work, again as long as people don't mind that it may reset the max/min temperatures (and humidity) up to 59 minutes after midnight. 

Here's how it clocked in with the check for whether the _hour_ had changed:

screen shot 2018-02-05 at 10 00 07 am

**Comment by tmleafs** [comment]
> lastCheckIn updates are no longer listed in the Events log ("Recently" tab of the ST mobile app) They were flooding the Events log, and 95% of the time happen at the same time as a Temp, Humidity, Pressure, or Battery report, so it's clear that the device has checked in. The Last Checkin tile will still be updated for every one of these events.

could the checkin be moved to battery report? so there is some events in the log. As with the buttons I sometimes don't press them for weeks might confuse a few users not seeing anything though it is displayed on the DH page. whatever we do might as well apply it too all the DH's make this a nice version 1.0 when its finally merged?

**Comment by alecm** [comment]
so - FWIW - I think we should have high/ low for whatever is in main tile - and work on the options to switch humidity/ temp in future - or maybe even have a couple of device handlers.  A little odd to have humidity both as a secondary in the main tile and a tile of its own...

**Comment by veeceeoh** [comment]
@tmleafs - I'm afraid I don't understand what you're asking.

Since changing the code to only display a lastcheckin event in the events log / recently tab if a message was received that could be parsed, I have not seen a single lastcheckin event. Not one.

This means that the only messages being received (for parsing anyhow) are temp, humidity, pressure, and battery reports. Oh, and the sensor name announcement, but you have to press the reset button to get that. 

So the check-in is just a synthetic event. If people want to make sure the sensor is online, look at the events log for battery reports. They are 90% consistently sent every 50-65 minutes, and that's true for all of my door/window sensors, and my leak, T/H, and motion sensors as well. It's fine to keep the Last Checkin tile, but really it should be called Last Received Report, because check-in is misleading and gives the impression that the sensor do some kind of network or connection check-in. If they are doing that, the hub certainly isn't passing on that information in any useful way.

The main reason I removed the lastcheckin events from being displayed is that it really takes away from what the T/H sensor is designed for: letting you know the temperature / humidity (and pressure for the Aqara model). I look at the events log of other sensors, and they really just keep things simple and stick to reporting what the sensor is designed to do.

**Comment by veeceeoh** [comment]
@alecm - I have to agree, and after playing with the secondary attributes text in the main tile, I just got rid of the droplet icon and the option to display the current humidity there too.

I'm about to do another (not quite finished yet) update for everyone to have a look at, and then decide on that.

**Comment by veeceeoh** [comment]
Notes from new commit (revision 3):

**New fixes**:
• Renamed some objects to more relevant names
• removed all preference defaultValues to allow the description text to display. There are checks for null values elsewhere so this doesn't hurt anything.
• removed `displayDuringSetup: false` because they aren't necessary
• added curly backets to some `if`... conditionals just to be sure it limits the lines called when passed
• changed some instances of `device.currentValue("object")` to `device.currentState("object")?.value`, where appropriate - based on some reading and looking at other professionally produced device handlers
• other formatting and minor fixes

**New enhancements**
• Reworked the routine for display secondary attributes on the main tile, removing the droplet icon and current humidity value (because it's already in another tile!)
• Added separate but combinable toggle preferences for displaying High/Low Humidity and/or High/Low Temperature with logic to use a shorter string when both are turned on to still fit all the information on one line - it looks pretty yucky when it's two lines. (screenshots below)
• Added a toggle preference for displaying temperature as an integer (but it's not implemented yet)
• Completely reorganized the preference page into distinct groups, with some reordering, and also changes to the text to remove redundant explanations and make them more concise. (screenshots below)

**Still to do**
• add back the previously used temperature parse routine, and link up the new display temp as integer boolean to choose which parse routine is used.
• Lots of testing by everybody, hopefully

img_2177

img_2178

img_2176

img_2179

img_2180

img_2181

img_2182

**Comment by tmleafs** [comment]
@veeceeoh are you happy for me to make the changes to all the other DH's in this commit?
Which are all the preferences changes (moving it, adding selections, changes in text, removing displayDuringSetup & default values)

removing lastcheckin from event log

Do we also rename "Last Checkin:" on the DH page to "Last Event:"?

**Comment by alecm** [comment]
@tmleafs  - sadly, my temp/humidity has yet again lost its pairing - annoying - will try later but am at work - so it won't be for a while
@veeceeoh this is looking great - 

One thing -  (we can open a separate issue) -   could we add one of the battery icons that y'all were playing with before, even if it isn't perfect across platforms?    [or is that something really not reliable enough yet? ) - I'll hold off on this for now if it's a distractor.

I really like high/low temp and humidity in the main tile!!!

**Comment by foz333** [comment]
I'll install it now, but i'm at work so I'll check results of code in few hours when I get back.

**Comment by alecm** [comment]
On the original temp - need to remove letter "a" at end of line 102

**Comment by veeceeoh** [comment]
@alecm - I'm just working on the Aqara T/H device handler for now, and after everyone's happy, then the changes can be applied to the original T/H device handler code, of course removing irrelevant sections like everything to do with pressure readings.

**Comment by veeceeoh** [comment]
@alecm - I removed that "a" - good eye! It's not in my working code that I'm using to test, so I'm not sure how it got in there.

To make additional commits to a Pull Request without actually merging it, you need to view the branch for that Pull Request, go to the file, edit, and then merge the commit. One way to access the branch is a link at the bottom of this discussion, here:

screen shot 2018-02-06 at 12 05 02 pm

**Comment by foz333** [comment]
@veeceeoh - first things first... Wow, you've put in some time there. New additions look good and setting very cleanly done. It is 2204 so my clocks will tick over in a couple hours. Unfortunately encountered some real life issues (Paris is under attack by mother nature, my temp and leak sensors are being regularly monitored) earlier so not had new code on very long. I'll see if I can set up one of my spare aqara temp sensor and throw it in fridge then on radiator to give a good span of temps to record.

screenshot_20180206-220148

**Comment by foz333** [comment]
Is there anything like that looks enough like a battery icon for the left tile? Without text it's a little ambiguous. For the record, all my devices are android

**Comment by alecm** [comment]
@veeceeoh - not "great eyes" - it just wouldn't save for me and I looked at the line :-)  Thanks for the instructions!

**Comment by veeceeoh** [comment]
@foz333 - Wait a second... You have 0.1 precision on your temperature display! I will have to try changing to Celsius for my hub's location setting again to test that. Perhaps SmartThings's built in temperature parse routine only provides integer values for Fahrenheit reports?

As for the battery icon - yes, if you'd like to try one. @tmleafs and I were going back and forth trying to get an icon that would position acceptably on both iOS and Android. It was very difficult, especially because the .png files I was saving on a Macintosh weren't displaying for him. In my last test, I installed the same program that worked for him to edit the icons and he hasn't had a chance to try those out.

If you don't mind, then try changing line 127 to this:

`            state "battery", label:'${currentValue}%', unit:"%", icon: "https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/images/xiaomi-battery-trans-icn.png",`

...and let me know if it displays for you.

Thanks!

**Comment by foz333** [comment]
Icon is a no-show for me too... 
screenshot_20180206-223911

**Comment by veeceeoh** [comment]
@foz333 

Okay, one more try, if you have time - how about this one?

`state "battery", label:'${currentValue}%', unit:"%", icon: "https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/images/xiaomi-battery-icn.png",`

**Comment by foz333** [comment]
No ball... Same as above blank space. 
In reply to your previous comment I paired a new aqtemp sensor and it's showing int values so assume numbers above are based on old data.

No battery on this SS as new sensor just testing the min max values. Sensor was on radiator, now in fridge.
screenshot_20180206-230831
screenshot_20180206-230813

**Comment by foz333** [comment]
Logs all look good... 
202cb0bf-961e-45d1-881f-d7fc67f57153  23:14:22: debug Testing XAq Temp Sensor: Parse returned [name:pressure, value:1005.8, unit:mbar, isStateChange:true, descriptionText:Testing XAq Temp Sensor Pressure is 1005.8 mbar]
202cb0bf-961e-45d1-881f-d7fc67f57153  23:14:22: debug Testing XAq Temp Sensor: Parsing description: read attr - raw: C5B40104031C000029ED03140028FF1000294A27, dni: C5B4, endpoint: 01, cluster: 0403, size: 1C, attrId: 0000, encoding: 29, value: 274a290010ff28001403ed
202cb0bf-961e-45d1-881f-d7fc67f57153  23:14:22: debug Testing XAq Temp Sensor: Parse returned [name:humidity, value:21, unit:%]
202cb0bf-961e-45d1-881f-d7fc67f57153  23:14:22: debug Testing XAq Temp Sensor: Parsing description: humidity: 20.75%
202cb0bf-961e-45d1-881f-d7fc67f57153  23:14:22: debug Testing XAq Temp Sensor: Parse returned [name:temperature, value:13, unit:C, descriptionText:Testing XAq Temp Sensor temperature is 13C°, translatable:true]
202cb0bf-961e-45d1-881f-d7fc67f57153  23:14:22: debug Testing XAq Temp Sensor: Parsing description: temperature: 12.7

**Comment by veeceeoh** [comment]
@foz333 - Thanks for testing those icons. I think I give up for now, because I don't know why they won't display on Android devices.

Some time after 00:00 you should see a Live Logging debug message of "Resetting daily min/max values to current temperature of XX". It may not happen until close to 01:00. The first report after 00:00 will trigger the reset.

**Comment by foz333** [comment]
@veeceeoh no worries, my kids get up around 6am so I too will leave it for now... I suspect I'll miss that message. 
I'll have a bash at the icon tomorrow when I'm on PC instead of tablet.

**Comment by bspranger** [comment]
Is this ready to merge?

**Comment by tmleafs** [comment]
Not been tested enough Wont be merged till @veeceeoh has also ported it to the original temp. I feel once this is ready it will be be our version 1.0 as after this I can't see us adding any more features it will just be bug fixes

**Comment by foz333** [comment]
@veeceeoh ... Good news i think I know why your icon is not working.  Well I'm down 2 possibilities both of which can be easily rectified.

1.  https, smarthing  can't access a secure site. So use http link
2. Your PNG is bad

To test I just grabbed any png URL from Google in roughly correct size and pasted in.
... Not pretty but you works
screenshot_20180207-232156

**Comment by veeceeoh** [comment]
@foz333 - Thanks for the further research! I will check into the https theory, but I still think it's something about the way I'm saving the .png file. I have tried saving files from four different programs now, and none of them display on Android, but all display just fine on iOS (even with an https link).

I think the battery icon issue shouldn't hold up this update, so can we continue to look at it afterwards?

Here comes the (hopefully) final commit for testing.....

**Comment by veeceeoh** [comment]
I've just merged what I hope is the last commit.

It's working as it should for me, but with my final pieces put into place during free time at work, I really want to put it through some testing tonight with how it deals with a newly paired device, and frequent/rapid temperature/humidity reporting (by blowing on it and putting it into my freezer.) If anyone else can do the same kind of testing, that would be great!

If everyone approves, then we can merge this pull and I can apply all relevant new code to the "original" T/H sensor device handler for another Pull Request - which will need testing by anyone with an "original" T/H sensor, since I don't have one!!!

**Notes from new commit (version 4):**

**Fixes**
• Removed `defaultValue: false` in `preferences{}` because `defaultValue` defaults to _false_ already!
• Completely rewrote the re-added C/F temperature conversion function because the building the map for the `createEvent()` is handled in `parse()`
• Added description to "_Display temperature as integer_" setting to note that it only takes effect on the next temp report and the min/max temps are always displayed as integer
• Removed all current humidity tracking code from previous code commit revision
• Added comment line to secondary attributes to allow users to enable display of (black) droplet icon if they wish
• Added commented out Celsius appropriate `backgroundColors` set for temperature / temperature2 tile definitions, with instructions on how to switch from the Fahrenheit appropriate color set
• Edited the header comments section to remove all the outdated update information, and added "_Version 1.0_" to the top and also information about contributors, and edited the "Known issues" section
• Other minor fixes / formatting

**Enhancements**
• Reinstated the old temperature conversion routine, rewritten, in order to link to the "_Display temperature as integer_" toggle setting
• Added more useful and relevant comments to explain code functions

**Still to do**
• **Test to make sure this code overhaul works as intended**
• Test pairing / re-pairing a device to make sure that battery runtime gets set, and min/max values kick in as soon as initial temp/humidity reports are received
• Consider whether a min/max temp and min/max humidity reset toggle should be added to the settings page
• Decide whether `section {}` in the preferences actually does anything in a device handler. The Developer Docs seem to indicate sections are only used for SmartApp preferences, and I don't see them displayed on my iPhone. What about on Android???

**Comment by alecm** [comment]
So,  this looks great - the battery is not *perfect* but that can’t be helped given cross-platform disjointure - it’s hugely better to actually have an icon than not.

 I’d like to suggest that we take a few days with this so we have time to test before pushing it out.  We’re all working and most of us only have a subset of devices . Great job, Keith! @veeceeoh

**Comment by veeceeoh** [comment]
@alecm - The battery icon is not part of the most recent commit. I don't even have that file and don't know if it will work on iOS devices. Again, I think it best to wait until we figure out how to get the appearance to be acceptable.

I agree - there's no need to rush on releasing this update. Way better to be absolutely sure it works.

**Comment by veeceeoh** [comment]
I got a chances to test my latest update (version 4) with the pairing process, and discovered the Min/Max temp code was allowing non-integer values to be displayed in the secondary attributes line. 

Unfortunately, there just isn't enough room for Min/Max Temp and Humidity to be both displayed on one line with a max temp over 99 if temps are displayed with 0.1 precision.

So now the values are converted to integer first, and I had to put in a safety check for null values (which only happen when the sensor is first paired.) It now works perfectly, and no errors are seen.

In fact I am very happy with how quickly things get set up upon pairing the device. Some good advice is to blow on it right after it is paired to get some values to show up.

The battery still shows up blank upon pairing as it does for all Xiaomi devices. Pushing the reset button doesn't supply battery voltage information until _after_ the first battery report happens, so we just need to remind users there's a 50-60 minute wait for a value to show up.

The only outstanding issue I've noticed is that the main tiles color doesn't always seem to correspond to readings (in Fahrenheit). A temp of 22F had a yellow background and 80F had a green background. I've been under the impression that colder temperatures would have blues/greens, and as you go up to warmer temperatures, to yellow, orange, and then red. Is that not correct? Interestingly, the color of the circle for temp events in the "Recently" tab don't always match the color of the main tile. Very strange, because the color list values for the "temperature" and "temperature2" tile definitions are the same.

Besides the tile color issue, I feel the code is ready for release. I'd love to hear back from all of you (especially if you've got an Aqara T/H sensor and can try it out.)

**Comment by foz333** [comment]
@veeceeoh i downloaded your image and uploaded it to imghost and pasteboard... 
http://imghst.co//69/UejaBHH~_n.png 
https://pasteboard.co/H6FXCKV.png
imghst works
pasteboard does not
... so for some reason Androind doesn't like https (well at least the 2 we tried).  
I don't know if you can get gitbut to publish http so maybe find another repository/server to host image?
if not you can use this @ 127
            state "battery", label:'${currentValue}%', unit:"%", icon: "http://imghst.co//69/UejaBHH~_n.png",

That said, the image renders a touch on the large side for me (android in 1080x1920 pixels),  but nothing serious.

screenshot_2018-02-08-13-12-34

**Comment by tmleafs** [comment]
@foz333 I was able to create ones that worked fine on github https they were black if @veeceeoh tried to modify one of mine to a grey it broke it. I believe it cant handle layers on png files all mine have been one layer its just a guess

**Comment by foz333** [comment]
@tmleafs can i have a link to any of your hosted icon pngs... could be something weird about us only being able to access our own repositories.  If i cant access your png could be that.

I literally just downloaded and saved @veeceeoh's created png (no modifications) and it worked from a different source.

**Comment by alecm** [comment]
@veeceeoh re: "The only outstanding issue I've noticed is that the main tiles color doesn't always seem to correspond to readings (in Fahrenheit). A temp of 22F had a yellow background and 80F had a green background. I've been under the impression that colder temperatures would have blues/greens, and as you go up to warmer temperatures, to yellow, orange, and then red. Is that not correct? Interestingly, the color of the circle for temp events in the "Recently" tab don't always match the color of the main tile. Very strange, because the color list values for the "temperature" and "temperature2" tile definitions are the same."

That's because once you get down below 40 (which is nice and blue) it's assuming that you're getting into Centigrade.   It should be even bluer at 22F  but instead we're getting a yellow as if it were a warm 22C.    Hope that can be fixed someday - but it's not a hold up I'd say.

**Comment by veeceeoh** [comment]
@foz333 - Here's one that @tmleaf worked on with an https:// link - https://image.ibb.co/gcoHym/weather12_icn_3xnew.png

To see our previous attempts with getting the icon to work both on iOS and Android, see the comments in Issue #66.

**Comment by foz333** [comment]
I've updated and the new changes all working/looking good... Just out of curiousity I tried with the link you gave above to @tmleafs image and that looks okay for me. Obviously color is out and it has the vestiges of the old icon but size wise that looked like a winner.

**Comment by veeceeoh** [comment]
I am now going to draft release notes to post in @bspranger's ST Community Forums thread for when these DTH updates are release.

**Comment by alecm** [comment]
BTW all my devices (button original, motion original, aqara motion, temp original, temp aqara are reporting battery fine with your most recent

**Comment by veeceeoh** [comment]
Looking at the two button DTHs, there's some small code improvements and further changes to the preference settings page I'd like to make. I will test it on my button tonight and then make commits to this Pull Req.

**Comment by tmleafs** [comment]
Nice work everyone! only inconsistencies I could find I just committed a fix for

**Comment by bspranger** [comment]
Sorry for the absence, I am remodeling my bathroom and nearly complete, so all my time has been focused on that and the kids.

Is this ready to be merged?

**Comment by veeceeoh** [comment]
Can we wait until tomorrow? I just want to test the revised button code.

**Comment by veeceeoh** [comment]
I still have to test the revised button code, but here's what I propose to change in the preference settings page:

img_2211

There wasn't any explanation to the two modes, and it needed a heading to be consistent with the other DTHs and moving the momentary delay setting below the mode toggle seems more logical.

I will set up the 2 second default in the code so that the description help text is displayed in preferences.

Thoughts?

**Comment by bspranger** [comment]
Sounds good to me

**Comment by alecm** [comment]
I actually don't understand 'momentary release delay' at all -  sorry!

**Comment by alecm** [comment]
And - at least on the original - if I keep pressing down - it does not send a release until I release it 
(I held for 15 odd seconds) 
image
I don't have an aqara button - so that might work for that - but shouldn't be done on the original
That's maybe why I don't understand 'momentary release delay'

**Comment by alecm** [comment]
Also - I vote for something like 'Momentary is like a push button, you push it, lit spring back, and something happens.  Toggle is like a button you push and stays pushed until you push it again and it lets go".  (Needs work but has to be more user-friendly).

**Comment by alecm** [comment]
But - happy to change the text on another release - as long as we don't push this to the original.

**Comment by veeceeoh** [comment]
@alecm - This is exactly the problem. I see a lot of users not understanding how it works. 

The button hardware itself does not have a momentary function at all. You press it, and it sends a single message at the exact moment you press it. That's all. Holding it down does nothing, and it does not send a message when you release the button.

So we have to synthesize a "release" event in the device handler code, because some SmartApps and devices being controlled want to see a "pushed" and "released" event.

But then if you want to simulate a momentary button, you need to know how long it's held for. So what is the delay after you press the button until a "released" event is sent? That's what the time in seconds preference is for. Call it a "delay until release event" or "how long to simulate button held", it's just a matter semantics to me. But I'm trying to figure out what explanation will help most people understand, because it hasn't been clear enough, I believe.

Hopefully the Toggle mode explanation is easier to understand. I have loads of electronic devices that use a toggle on/off button. Push - it's on. Push again - it's off. Pretty basic.

Any suggestions on clearer text which isn't 3 paragraphs long like I just typed would be awesome.

**Comment by veeceeoh** [comment]
Also, I haven't changed anything in either Button DTH yet with regards to this. All of my explanation of how the two modes work is exactly how the code runs as of now in this Pull Request. I wasn't planning on changing that - the two mode options are great. It just needs a better explanation. People are getting confused.

**Comment by alecm** [comment]
My point was only that the original button *does* have a release event (see my log)  and want to make sure we don’t change it there.   I don’t have an Aqara button - pretty disappointing they decided to remove the release event.  Could I suggest we move ahead with release without this update- code freeze this morning given that it’s been tested so thoroughly - and then move forward with better text, functionality, in next release?   It can happen fast.

**Comment by veeceeoh** [comment]
Ahhhhh, my apologies. Well, I got confused, because I looked at the preferences section of both botton DTHs, and then focused on just the Aqara button DTH. Looking at the rest of the code of the "original" button it's obvious that it has pushed _and_ released message capability.

However, I was totally thrown off by this preference in the "original" button DTH:

> Minimum time in seconds for a press to count as "held"

I searched through the code and that isn't even used anywhere! Why is that preference in there?

**Comment by veeceeoh** [comment]
So anyhow, you're right - I can look at the minor edits for the two button DTHs later.

I'm gonna merge it!

**Pull request merged**
