### PR TITLE
Fix Original Xioami Button always pushed

### PR DESCRIPTION
**Pull request by tmleafs**
and other inconsistencies between the two buttons

### CODE REVIEW

**Comment by bspranger** [comment]
See my comments I believe there are inconsistency with "push" and "pushed"

**Comment by bspranger** [comment]
Look at the changes tab of the pull request.  I put a comment in.

**Comment by tmleafs** [comment]
I have looked everywhere cant see any comments, would of received a email if I did too

**Comment by bspranger** [comment]
In the aqara dh, line 120.  The send event sends the state as pushed, but above you changed the attribute from pushed to push.  I am not sure if those have to be the same or not, but I believe they do.

**Comment by tmleafs** [comment]
Changed all pushed to push

It would of still worked you just didn't get the blue circle in the recently tab

**Comment by tmleafs** [comment]
Going to next the hold button function

**Comment by tmleafs** [comment]
Going to next the hold button function

**Comment by bspranger** [comment]
So this should not be merged?

**Pull request closed without merging**
