### PR TITLE
Code overhaul of both motion detector DTHs (Needs testing)

### PR DESCRIPTION
**Pull request by veeceeoh**
I have gone through all of the Aqara Motion Detector DTH code, and after removing unnecessary function calls and lines of code, removing error-prone code, and looking at the motion reset preference issue, ~~I have discovered that **this device is capable of continuous motion detection**!~~ I have fixed the issue with the motion reset setting being ignored, and got the DTH working as it should.

I am still using the `runIn()` scheduler to reset back to the 'no motion' / `inactivity` state that was already in the code, because in my testing it seems to work just fine. The default is now 60, the same as the hardware's motion detection reset time, but it is set in the code rather than by adding `default: 60` to the preference line.

I am extremely happy with how the code is working, but I really want some others to test it to see how it works for them.

I also need to go through the "original" motion detector code to clean it up as well.

Note that I created this Pull Request commit off of @tmleafs Standardization branch, so it should be merged first and this one afterward.

### CODE REVIEW

**Comment by alecm** [comment]
This is really interesting - I'll be doing some testing.   One caveat - it looks like at least the original diatomic has a test mode per https://docs.google.com/document/d/1zYOjPk4Fttndztbq7hqnCrVLcNKX_AI4uWWjXL6h3nw/mobilebasic

I've always found that's true with my Aqaras - for first couple of hours after pairing they can reset motion almost instantly - then they go back to at least 60 seconds.   Pushing the button on them can put them back into test mode.   (With instant 5/sec  reset) 

Just something to take into account when testing. Presumably if you haven't pushed the button in a while it's out of test and into "normal" mode.

**Comment by veeceeoh** [comment]
Oh snap!

Yes, in my testing, I pushed the reset button to check if it sent any battery voltage data like some other Aqara sensors (it only sends it's model name, not the battery data).

This morning the hardware is now blind to another motion event for 60 seconds.

That's a shame. I was pretty excited about it. Either way, I got all the issues worked out! Please still free to test, because that is needed.

Thank you for letting me know about the test mode. I had no idea.

**Comment by alecm** [comment]
Bummer! @veeceeoh   - I know the feeling....

**Comment by alecm** [comment]
Hello - so with the Aqara motion sensor I haven't had effective battery reporting since I installed it on one sensor this morning.    I just saw this in live log as I think it was trying to report
image

My line 200 is
def MsgLength = cluster.data.size();

(different from yours because I was messing around with some background colors for lux - but that shouldn't make a difference).

I'm going to reinstall (just to make sure I didn't put something extra in there)  and see if the problem is still there - maybe something to do w/ the <1000 math?

**Comment by veeceeoh** [comment]
Line 200 on my code update is just a closing curly bracket, so that's not the same as the code you're using.

There is a `log.debug cluster` line well before def MsgLength = cluster.data.size(); so your log should have that after the  "...pasting: catchall: ...." and before the null error.

The `log.debug cluster` live logging output would be really long, but starting with "SmartShield"...

I think you should try re-applying the new motion sensor DH code, and then see what line the error shows up on.

I see that the regular battery reports aren't being logged as events on my phone, but I'll have to go home to look at my live logging window there to see what's going on. It should be an easy fix, and definitely not the raw voltage divide by 100 change. That's working fine on everything else of mine (at least the normal divide by 1000 calculation which is the most important thing.)

**Comment by alecm** [comment]
Yeah - I've reapplied - and have put the motion sensor in a place where it can see no motion - so should get a better report (or show it's fine and I messed it up) fairly soon...

**Comment by veeceeoh** [comment]
So I've at least checked the device states list for battery of my Aqara motion sensor, and see it's not been logging battery report events since yesterday. So I did something to break that, and will fix it later.

**Comment by alecm** [comment]
So I reapplied - only change I make is the name so I don't overwrite my current DTH - and exactly at 55 minutes from the previous I got 
image

Not seeing any log debug message, I'm afraid 

Just to be sure - I used the link you posted recently in the Smart Things Community (though this morning I used Github

**Comment by alecm** [comment]
Good luck!

**Comment by veeceeoh** [comment]
I figured it out. I had started to change a variable in the function that reads in the battery data, from `cluster` to `catchall`, and missed a few instances.

It should be fixed and work correctly now.

**Comment by alecm** [comment]
Cool - just applied it to my office motion sensor -  have to leave in an hour for the evening - but hopefully get a report before then...

**Comment by alecm** [comment]
Just got a perfect batter report ! Looks good!

**Comment by alecm** [comment]
*battery

**Comment by veeceeoh** [comment]
Me too, and no errors in the live logging page! I think this is in the final testing stage now, and I'm going to apply all working fixes to the "original" motion detector sensor DTH.

**Comment by alecm** [comment]
I have one of those too - will test in the morning (out for rest of evening)  - though I have iPad with me :-)

**Comment by veeceeoh** [comment]
Sounds great - I'm sure you'll receive a notification when I've committed the changes to this pull request.

**Comment by veeceeoh** [comment]
I have gone through all of the code of the device handler for the "original" Xiaomi motion detector, and fixed / edited it to match the updated Aqara MD code.

Everything is the same except for no illuminance value message function, a different `fingerprint profileId` line, and only attribute ID `FF02` in a catchall message triggers the battery voltage data parse routine.

I also realized that the order of merging the Pull Requests should go like this:

merge `veeceeoh-patch-1` into `standardization`
merge  `standardization` into the base master branch
merge  `code-overhaul` into the base master branch

**Comment by alecm** [comment]
Tried to do a pull but didn't get it right so closed.  Don't have a lot of time right now to figure it out , so - 
1.  Need to remove comma at end of line 72 on the Aqara Motion Sensor - not compiling without it

2. I'd propose this text for the timeout sensing preference - wordy but I think it's worth explaining - always leads to confusion. Also, although it's not pairing that strictly puts it into TEST - it has same effect because you always push button during pairing. " 

"This setting only changes how long MOTION DETECTED is reported in SmartThings. The sensor hardware in NORMAL mode remains blind to new motion for 60 seconds after any activity. \n\n(NOTE: Pairing or pushing button on sensor puts it into TEST mode which recognizes new motion every 5 seconds. After 2 hours it reverts to NORMAL/60 second mode.)"

**Comment by veeceeoh** [comment]
I removed the comma, but am going to hold off on changing the setting explanation text (want to hear other opinions).

Here's how to make edits to an existing pull request branch:

1. Go to the main Code tab view of bspranger/Xiaomi.
2. Click the Branch: button to change to the branch you want to make an edit to (in this case was veeceeoh-patch-1).
screen shot 2018-02-11 at 8 54 25 am
3. Navigate the repository file structure until you're viewing the code you want to edit and edit it.
4. After editing, if it's a fix you're sure needs to happen, choose "Commit directly". Otherwise - again in this particular case - creating a new branch will start a Pull that's on a Pull that's on a Pull.

**Comment by alecm** [comment]
I agree with getting more opinions on text.   I do think it’s worth explaining to avoid future requests.  Besides, it’s a good feature (to help you test location when setting or moving.)

**Comment by alecm** [comment]
And thanks for the detailed instructions - I’d managed once before but this time I ended off with an enormous commit by mistake!

**Comment by alecm** [comment]
Just got around to testing the one for original motion sensor - I only have one left.  I just repaired so haven't gotten battery yet, which is fine.  

I've noticed one thing 
- Changed battery toggle doesn't work - if I change it nothing shows up in the main screen and it doesn't stay changed -  is this expected behaviour because battery reporting hasn't started yet? 

Thanks

**Comment by alecm** [comment]
Actually battery change seems also broken on the Aqara motion sensor - I just tried a reset on one that's reporting regularly with most recent DTH and the date didn't change for 'Battery Changed'

**Comment by tmleafs** [comment]
I cant see any reason for that @alecm do you have any other devices your could try?

**Comment by veeceeoh** [comment]
@alecm - I just tried the battery changed toggle with the updated Aqara DTH, and it worked fine.

I'll have to try the pairing process with the DTH again, but what should happen if it is paired using the "Add a Thing" method is that the battery changed date automatically gets set to the current date.

This happens in the install() function, which gets called right after any sensor shows up ready to be renamed in the "Add a Thing" method. I have gone through this more than a dozen times with different sensors to test it. I even put in a debug log output seen in live logging that says "Setting Battery Changed to current date for newly paired sensor"

I don't have the "original" T/H sensor or motion sensor, however, so I have no way to check if the install() function gets called upon pairing. And of course a lot of users seem to give up on pairing using the "Add a Thing" method, and use the catchall method. So I guess I could put in a check in elsewhere to see if Battery Changed is blank, and then set it. Or just tell users to toggle it in the preferences.

**Comment by alecm** [comment]
Just tested on xiaomi orig button (recopied DTH from standardisation pull just in case) and it worked fine.   My only other two devices are the two types of temp - which I can try later (don't have new Aqara button, leak sensor, or any door sensors)

**Comment by alecm** [comment]
False alarm on the Aqara Motion Sensor Battery Reset - I just repasted and tested with a couple more sensors and it's ok.  Sorry.

**Comment by veeceeoh** [comment]
Good to hear. I'm gonna add that code in `configure()` anyhow.

Also, I will try testing what happens on pairing with the only "original" Xiaomi devices I have - 4 door/window sensors.

**Comment by alecm** [comment]
unfortunately the pairing on my original motion sensor didn't stick (even though it had paired to hub) - will try again...    I'm at that almost 32 level...

**Comment by veeceeoh** [comment]
Well, that changed definitely worked. Here's the log from re-pairing my Aqara motion detector:

screen shot 2018-02-11 at 12 48 28 pm

So it appears that the `installed()` and `configure()` functions get called or run simultaneously.

I also tried re-pairing an "original" D/W sensor without the revised code, and the Battery Changed date was auto-populated.

I like having the log message if possible, so I'm going to update all DTH's with the revised code to check if `batteryRuntime` has been set yet.

**Comment by veeceeoh** [comment]
> unfortunately the pairing on my original motion sensor didn't stick (even though it had paired to hub) - will try again... I'm at that almost 32 level...

Totally off-topic: I have just ordered a new [Hubitat](https://hubitat.com) hub. It was created by a team of very active SmartThings users including the guy who made the Rule Machine SmartAp, runs 100% locally with all Z-Wave and ZigBee devices, and has much greater access to ZigBee protocol (or so they have said). And I think it doesn't have the 32 ZigBee device limit, either.

The programming language is Groovy, and much of ST device handler and SmartApp code can be directly ported over. It's my hope that with the greater access to ZigBee commands and messages, that I can get all Xiaomi devices working the way they should. Of note: someone has already made a SmartApp that allows you to link between SmartThings and the Hubitat hub, using virtual switches / devices. I don't plan on ditching my ST hub anytime soon, so that's a great thing!

**Comment by veeceeoh** [comment]
Paired an "original" door/window sensor with the new code, got this in the log:

screen shot 2018-02-11 at 1 06 42 pm

And here's what I see when I toggle the Battery Changed setting in preference and save:

screen shot 2018-02-11 at 1 09 02 pm

Looks beautiful! I'm going to do commits on this to all the DTHs.

**Comment by veeceeoh** [comment]
Good thing I was doing this testing - I just discovered the door/window DTH updates the "Last Opened:" in the main tile any time an open or _closed_ event occurs. So that needs to be fixed so it only refreshing on an open event.

**Comment by veeceeoh** [comment]
Now merging into `standardization` branch!

**Pull request merged**
