### PR TITLE
address SHM issue maybe

### PR DESCRIPTION
**Pull request by foz333**
fire becomes smoke
smoke becomes detected

### CODE REVIEW

**Comment by foz333** [comment]
Tested by @emilakered and me. Addresses issue #96 
Merge please. But check the  file still works as there was some kind of names pace issue last time.

**Comment by veeceeoh** [comment]
I have added the new battery icon to this pull.

The namespace & author match, so it should merge fine.

Can @foz333 & @emilakered please check that the new icon is displaying correctly?

Then I'll merge it, and @foz333 you are welcome to announce the update on ST Community Forums.

**Comment by bspranger** [comment]
Should this be merged?

**Comment by foz333** [comment]
@veeceeoh you changed the battery tile into a humidity tile.

I'll change the default battery high as 3.25 as this is a more accurate start point for these batteries.

I'll rip the code from another DH and put this in, then it will good to go.

**Comment by foz333** [comment]
@bspranger / @veeceeoh this should be fine now, smartthings seems to be having a global ideDH failure so nobody can modify code just now so cant be test.  maybe laters.

**Comment by foz333** [comment]
@veeceeoh @bspranger can you merge this please

**Pull request merged**
