### PR TITLE
Smoke Sensor DH

### PR DESCRIPTION
**Pull request by foz333**
Not picking up any errors and principal functions are working...

Detects smoke
Detects test
Alarm can be cleared / stopped with physical button press

Have used @veeceeoh / @tmleafs preferences and tried to keep layout as per other DHs

+ updated readme to account for new sensor

### CODE REVIEW

**Comment by bspranger** [comment]
@foz333 let me know when this is ready for prime time.

How do you like the sensor?

**Comment by foz333** [comment]
This is good to go.

The other zigbee.command stuff i'm trying is just fluff (optional extras)

**Comment by bspranger** [comment]
Adding support for the Xiaomi Smoke Detector!

**Comment by bspranger** [comment]
@foz333 thanks for your contributions!  These DHs are really awesome now that we got a team working on them.

**Comment by bspranger** [comment]
This DH will not import from Git in the IDE due to errors...

**Comment by foz333** [comment]
i think its an issue with how i created the file that contains the code rather than the code itself.

See if you can paste the code into a new file and it should work

**Comment by bspranger** [comment]
I had to change the namespace and author to bspranger.  Then ST allowed me to import the DH.  They must have to match the GIT repo.

**Pull request merged**
