### PR TITLE
Battery min/max state tracked

### PR DESCRIPTION
**Pull request by snalee**
Added the endpointid fingerprint. It seems to make it so that Smartthings will detect and present the Xiaomi device as a valid thing. There's a delay between when the device pairs and when the app shows it as a thing.

Changed the battery calculation to use the average of min and max of the battery value. I was noticing the battery percent ping-ponging between two values, so this will smooth out the reading.

### CODE REVIEW

**Comment by bspranger** [comment]
Before I merge the changes for the battery I would like to get an understanding if the devices are working more reliable.  Currently I feel like my Xiaomi devices are performing better than they have ever performed.  Not sure why the end points need to change because the devices I have automatically add without having to perform the catchall.

Looking for more feedback.

**Comment by snalee** [comment]
Sure.

I was using your original code before my changes, but it was not showing up
as a thing until I added the other endpoint by Gavin. I just read the
documentation on the fingerprint and I think I can clean up that bit of
code some more.

Yeah, the code was working fine for me as well. The changes I've made are
related to fixing the battery level ping-ponging (going from 98 to 99 to 98
to 99, etc.), and to try to reduce the number of times battery info is
sent. Not sure if my change will work yet, but I'm just testing it out. I
also changed the voltage range to 2.7 to 3.3 based on the apparent
documentation, but I also already knew that battery is spec'ed to be
theoretically 3.4 v max.

In any case, it's up to you if you want to merge after testing. I just
figured it'd be better to have a single source for the DH.

**Comment by bspranger** [comment]
I am totally wanting to have a common code.  So I am not against integrating your code.  I just want to understand it and make sure we are making forward progress.

Groovy is completely new to me, I am usually developing embedded C, so it has been a lot of hunting and pecking to get what I have working.

The Xiaomi devices are awesome, small, quick to respond, great battery life.  I want to make sure these things are working the best they can.

**Comment by snalee** [comment]
Sounds like a plan. I'm new to Groovy as well, but I'm very familiar with
Java, C and C++, so it's not too hard. The hard part for me is not knowing
the Smartthings framework (I don't feel like learning it), and the Xiaomi
protocol (no documentation). But I just started working on this the past
few days so I'm still learning as well.

I think where it is now, it's pretty good for most needs and I don't plan
to spend too much time doing this. I only wanted to make sure the battery
level readings were usable and to make it simple to add to Smartthings.

I just wish the responses for some of the events were faster (like the
button press takes too long to trigger my automation).

**Comment by bspranger** [comment]
Check out this link.

http://zigate.fr/produits-xiaomi-compatibles-zigate/

It has all the zigbee messages broken out.  Now we can parse the messages without guessing.

**Comment by snalee** [comment]
Oh sweet!

On the original Xiaomi door sensor, I noticed it doesn't do a zbjoin like
the Aqara version does.  Because of this, I can't figure out what it's
endpoint information is to get it to map to the DH. Do you know what it
takes to get ST to get a zigbee device to join the network? It can't be
something in the DH because it doesn't get associated with a DH until after
the zbjoin occurs.

**Comment by bspranger** [comment]
That is strange,  I have no issues with my original door sensors joining.   I have a ton of them.  Only 1 aqara door sensor.  So I am not sure there is an issue with the DH.

**Comment by bspranger** [comment]
I think you can see them in the catch all too. 
They are documented in the link I sent.

**Comment by snalee** [comment]
I see the catchall, but until ST does a zbjoin, it won't do a DH lookup.

**Comment by snalee** [comment]
The document isn't showing any of the status message either (ie. battery
value). I guess it doesn't really matter. The current code seems to have
everything working anyway.

**Comment by bspranger** [comment]
I will try to get these changes merged soon.  Haven't had a chance to get on the PC.

**Comment by snalee** [comment]
No worries. It would be nice if we could get these to a point where it can
be submitted and approved for public publishing. I'd really like to run the
buttons locally as the latency is annoying.

**Comment by bspranger** [comment]
merging changes from snalee

**Comment by snalee** [comment]
Maybe you should change the namespace and author to something different
than a4refillpad? It's no longer the same and it will reduce confusion in
the device handler list.

**Comment by bspranger** [comment]
I tried to do that once and it broke stuff.

Do you know what I need to change?  Because I agree that I need to change it.  But I think it needs to align with github somehow.

**Comment by snalee** [comment]
In this line, just change the namespace and author strings:

definition (name: "Xiaomi Aqara Door/Window Sensor", namespace: "a4refillpad
", author: "a4refillpad") {

I don't know why it would break github. It's only used by SmartThings.

**Comment by bspranger** [comment]
BTW all your changes are merged.

I will try to change it at some point soon.

**Comment by snalee** [comment]
Cool. I think I'm pretty much done mucking with the door and button code
for now. It's stable and works.

**Pull request merged**
